CruGlobal/plugin_ABDesigner

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/ABViewDataview.js
src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/views/ABViewDataview.js
src/rootPages/Designer/properties/views/ABViewDetail.js
src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyLinkPage.js

https://github.com/digi-serve/plugin_ABDesigner/issues/46

Migrate Dataview widget

---

src/rootPages/Designer/ui_work_object_workspace.js
src/rootPages/Designer/ui_work_object_workspace_popupFilter.js

The popup should be adjustable in size, and there may be some display bugs with the filter complex -- but it works now

Add filter to object

---

src/rootPages/Designer/ui_work_datacollection_workspace_properties.js

https://github.com/digi-serve/ns_app/issues/105

*Fix set query list in data collection workspace page

---

src/rootPages/Designer/properties/process/ABProcessTaskServiceInsertRecord.js

https://github.com/digi-serve/ns_app/issues/157

Fix "Set by previous step data"

---

src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/process/ABProcessTaskSubProcess.js
src/rootPages/Designer/ui_work_process_workspace_customBPMN_replaceMenuProvider.js

[add] implement initial Process Sub Task editor

Process sub task

---

src/rootPages/Designer/properties/dataFields/ABFieldFormula.js
src/rootPages/Designer/ui_work_object_workspace_popupFilter.js
src/rootPages/Designer/ui_work_query_workspace_design.js

https://team.digiserve.org/main/pl/s781fncgyp8pim1uhyswxis11c

Apply complex filter to the formular field

---

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/_ABViewDefault.js
src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/rules/ABViewRuleListFormSubmitRules.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormSubmitRuleExistPage.js
src/rootPages/Designer/properties/views/ABViewFormButton.js
src/rootPages/Designer/properties/views/ABViewFormConnect.js
src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyAddPage.js
src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyEditPage.js
src/rootPages/Designer/ui_work_interface_workspace_details_properties.js
src/rootPages/Designer/ui_work_interface_workspace_editor_layout.js

https://github.com/digi-serve/plugin_ABDesigner/issues/99
https://github.com/digi-serve/plugin_ABDesigner/issues/101

Fix button and connect elements of the form widget

---

src/rootPages/Designer/editors/views/ABViewLayout.js
src/rootPages/Designer/properties/rules/ABViewQueryBuilderObjectFieldConditions.js
src/rootPages/Designer/properties/rules/ABViewRuleListFormRecordRules.js
src/rootPages/Designer/properties/rules/ABViewRuleListFormSubmitRules.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormRecordRuleInsertConnected.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormRecordRuleRemoveConnected.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormRecordRuleUpdate.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormRecordRuleUpdateConnected.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormSubmitRuleClosePopup.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormSubmitRuleParentPage.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionFormSubmitRuleWebsite.js
src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionObjectUpdater.js
src/rootPages/Designer/properties/views/ABViewTab.js

https://github.com/digi-serve/plugin_ABDesigner/issues/100

Migrate submit & record rules

---

src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionObjectUpdater.js

https://github.com/digi-serve/plugin_ABDesigner/issues/110
https://github.com/digi-serve/plugin_ABDesigner/issues/111
https://github.com/digi-serve/plugin_ABDesigner/issues/115
https://github.com/digi-serve/plugin_ABDesigner/issues/116

Fix the record rule and condition container widget

---

src/rootPages/Designer/properties/views/ABViewFormConnect.js
src/rootPages/Designer/properties/views/ABViewGrid.js

https://github.com/digi-serve/plugin_ABDesigner/issues/99#issuecomment-1371687045
https://github.com/digi-serve/plugin_ABDesigner/issues/117

Fix those things

---

src/rootPages/Designer/ui_work_object_workspace_popupTrack.js
src/rootPages/Designer/ui_work_process_list.js

https://github.com/digi-serve/ab_service_process_manager/issues/39

*Fix .toDate consistency

---

src/application.js
src/rootPages/Designer/properties/process/ABProcessTaskUserApproval.js
src/webix_custom_components/customComponentManager.js
src/webix_custom_components/formioBuilder.js

see https://github.com/digi-serve/ab_platform_web/pull/249

Nh/fix formioBuilder

---

src/rootPages/Designer/properties/views/ABViewFormButton.js
src/rootPages/Designer/properties/views/ABViewFormConnect.js
src/rootPages/Designer/properties/views/ABViewFormItem.js
src/rootPages/Designer/properties/views/ABViewFormNumber.js
src/rootPages/Designer/properties/views/ABViewFormSelectMultiple.js
src/rootPages/Designer/properties/views/ABViewFormSelectSingle.js
src/rootPages/Designer/properties/views/ABViewFormTextbox.js
src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyAddPage.js
src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyEditPage.js

fixes https://github.com/digi-serve/plugin_ABDesigner/issues/154

add calls to `this.onChange()`

---

src/rootPages/Designer/properties/process/ABProcessTaskService.js

https://github.com/digi-serve/plugin_ABDesigner/security/code-scanning/7

Fix wrong use of "this" for static method

---

src/rootPages/Designer/properties/process/ABProcessParticipant_selectManagersUI.js
src/rootPages/Designer/properties/process/ABProcessTaskUserExternal.js
src/rootPages/Designer/ui_common_participant_selectManager.js

Add FilterComplex for scopeQuery on ProcessUserTask and fix bugs

Add scopeQuery for UserTask

---

src/rootPages/Designer/properties/process/ABProcessParticipant_selectManagersUI.js
src/rootPages/Designer/ui_work_process_workspace_model.js

https://github.com/digi-serve/plugin_ABDesigner/issues/169

*Fix "by Field" options in the Email task

---

src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyLinkPage.js
src/rootPages/Designer/ui_work_datacollection_workspace.js
src/rootPages/Designer/ui_work_datacollection_workspace_properties.js

https://github.com/digi-serve/ab_platform_web/issues/279

Filter Data Collection by another Data Collections Cursor

---

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/ABViewPivot.js

https://github.com/digi-serve/plugin_ABDesigner/issues/179

*Fix pivot widget

---

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/ABViewKanban.js
src/rootPages/Designer/properties/views/ABViewKanban.js

https://github.com/digi-serve/plugin_ABDesigner/issues/178

Implement detail & form page links to Kanban widget

---

src/rootPages/Designer/properties/views/ABViewFormConnect.js

https://github.com/digi-serve/ns_app/issues/232

+Add Filter by Connected Field to FilterComplex

---

src/rootPages/Designer/ui_work_process_workspace_model.js

Prevent errors when trying to pull a value from a Placeholder Panel

[fix] Placeholder Panels can cause attempts to save errors

---

src/rootPages/Designer/properties/views/ABViewScheduler.js

https://github.com/digi-serve/ab_platform_web/issues/345

Filter required column for Calendar Color field

---

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/ABViewPDFImporter.js
src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/views/ABViewPDFImporter.js

https://github.com/digi-serve/ns_app/issues/179

Add PDF import widget editor

---

src/rootPages/Designer/properties/views/ABViewPDFImporter.js

https://github.com/digi-serve/ns_app/issues/179

*Add Submit rule editor to the PDF Importer widget

---

src/rootPages/Designer/editors/views/ABViewPivot.js

https://github.com/digi-serve/plugin_ABDesigner/issues/206

*Migrate pivot widget on webix 10

---

.github/workflows/dispatch-web-update.yml
.github/workflows/e2e-test.yml
.github/workflows/merging-rules.yml
.github/workflows/pr-label-check.yml
.github/workflows/pr-merge-release.yml
README.md

- Automate Build, Version and Release

Auto Version

---

.github/workflows/dispatch-web-update.yml

fix dispatch location

---

src/rootPages/Designer/properties/views/ABViewFormConnect.js

- fix populate filter condition of form's connect widget to support compatible

*Fix compatible filter settings of Form connect element

---

src/rootPages/Designer/ui_choose_list.js

https://github.com/digi-serve/ns_app/issues/314
- Update load application list from myapps url in the Designer page to improve performance

*Update load application list from myapps url in the Designer page

---

src/rootPages/Designer/ui_work_object_list_newObject_api_read_response.js

- Fetch data of API Object from back end

Fetch data of API Object from back end

---

src/rootPages/Designer/ui_work_object_list_newObject_api.js
src/rootPages/Designer/ui_work_object_list_newObject_api_read.js
src/rootPages/Designer/ui_work_object_list_newObject_api_read_request.js
src/rootPages/Designer/ui_work_object_list_newObject_api_read_response.js

https://github.com/digi-serve/ab_service_appbuilder/issues/58
- Implement Key and Secret to API Object

Implement Key and Secret to API Object

---

src/rootPages/Designer/properties/views/ABViewConditionalContainer.js

- Fix show up the settings popup of the condition container widget

*Fix show up the settings popup of the condition container widget

---

src/rootPages/Designer/ui_work_query_workspace_design.js

https://team.digiserve.org/main/pl/e19y76x1npg1dpp5orrxaq3nqh
- Fix the query workspace page

*Fix the query workspace page

---

src/rootPages/Designer/editors/views/ABViewContainer.js
src/rootPages/Designer/ui_work_process_workspace_model.js
src/webix_custom_components/customComponentManager.js
src/webix_custom_components/formioBuilder.js

- Ensure dependencies, which are now lazy loaded in platform web, get initialized before use.
digi-serve/ab_platform_web#428

Initialize deferred dependencies

---

src/rootPages/Designer/ui_work_datacollection_workspace.js
src/rootPages/Designer/ui_work_datacollection_workspace_linked_dc.js

https://github.com/digi-serve/plugin_ABDesigner/issues/27
- Implement linked cursor option in DC builder page

Implement linked cursor option in DC builder page

---

src/rootPages/Designer/properties/dataFields/ABFieldCalculate.js

https://github.com/digi-serve/ns_app/issues/374
- Support datetime fields in calculate field formula

support datetime in calculate field

---

src/rootPages/Designer/properties/rules/ruleActions/ABViewRuleActionObjectUpdater.js

https://github.com/digi-serve/planning/issues/507
- Implement Current Date option to the record rule

*Implement Current Date option to the record rule

---

src/rootPages/Designer/ui_common_list.js
src/rootPages/Designer/ui_common_popupEditMenu.js
src/rootPages/Designer/ui_work_object_list.js
src/rootPages/Designer/ui_work_object_workspace_popupHeaderEditMenu.js

https://github.com/digi-serve/plugin_ABDesigner/issues/7
- Implement Object information

+Implement Object information

---

src/rootPages/Designer/ui_common_list.js
src/rootPages/Designer/ui_common_popupEditMenu.js
src/rootPages/Designer/ui_work_object_list.js

https://github.com/digi-serve/plugin_ABDesigner/issues/7
- Fix display "Information" menu item of object list

*Fix display "Information" menu item of object list

---

src/rootPages/Designer/properties/views/viewProperties/ABViewPropertyLinkPage.js

https://github.com/digi-serve/ns_app/issues/394
- Fix save link page values of the grid widget

*Fix save link page values of the grid widget

---

src/rootPages/Designer/properties/views/ABViewFormButton.js

https://github.com/digi-serve/ns_app/issues/89
- Add delete feature settings to the Form widget

+Add delete feature settings to the Form widget

---

src/rootPages/Designer/properties/process/ABProcessTaskUserApproval.js

With our recent changes we must have changed the values we save for the Form Builder Components.
- [fix] properly save the form builder components

Correct the values we are saving for the Form Builder Components

---

src/rootPages/Designer/properties/views/ABViewCSVExporter.js

https://github.com/digi-serve/ns_app/issues/416
- Close the popup when save

*Close the popup when save

---

src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/process/ABProcessTaskServiceAccountingBatchProcessing.js
src/rootPages/Designer/properties/process/ABProcessTaskServiceAccountingFPClose.js
src/rootPages/Designer/properties/process/ABProcessTaskServiceAccountingFPYearClose.js
src/rootPages/Designer/properties/process/ABProcessTaskServiceAccountingJEArchive.js
src/rootPages/Designer/properties/process/_ABProcessTaskServiceAccounting.js

https://github.com/digi-serve/ns_app/issues/424
- Migrate custom accounting app process tasks

Migrate custom accounting app process tasks

---

src/rootPages/Designer/ui_work_object_workspace_popupSortFields.js

https://github.com/digi-serve/ab_platform_web/issues/471
- Fix AB not defined in the sort popup

*Fix AB not defined

---

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/ABViewOrgChart.js
src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/views/ABViewOrgChart.js

https://github.com/digi-serve/planning/issues/569
- Add the OrgChart widget

Add the OrgChart widget

---

.github/workflows/e2e-test.yml
src/rootPages/Designer/properties/views/ABViewOrgChart.js

Clean setting properties of OrgChart widget

---

src/rootPages/Designer/ui_work_object_workspace.js
src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js

- Fix creating the connect field that link to itself object bug

*Fix creating the connect field that link to itself object bug

---

package-lock.json
package.json
src/rootPages/Designer/properties/dataFields/ABField.js
src/rootPages/Designer/properties/dataFields/ABFieldString.js

Add a checkbox and text field to collect max length value.
[#393](https://github.com/digi-serve/planning/issues/393)

Limit the maximum length of text field

---

src/rootPages/Designer/properties/dataFields/ABFieldDate.js

-  Add select option ( Less current date , Less or qual current date )
https://github.com/digi-serve/ns_app/issues/450

add select option & adjust UI

---

src/rootPages/Designer/properties/dataFields/ABField.js

- [fix] catch when no validation rules exist
no additional tests

Fix UI bugs

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

- add team inactive, canInactivate settings
Unit tests in platform web
https://github.com/digi-serve/ab_platform_web/issues/557

add setting fields for inactive, canInactivate

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

- Add settings for team strategy and colors

Add settings for team strategy and colors

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

- https://github.com/digi-serve/ab_platform_web/pull/586

Team Widget can edit assignments

---

package-lock.json
package.json
src/rootPages/Designer/properties/dataFields/ABFieldConnect.js
src/rootPages/Designer/ui_work_object_list_newObject.js
src/rootPages/Designer/ui_work_object_list_newObject_api_read_response.js
src/rootPages/Designer/ui_work_object_list_newObject_netsuite.js
src/rootPages/Designer/ui_work_object_list_newObject_netsuite_connections.js
src/rootPages/Designer/ui_work_object_list_newObject_netsuite_credentials.js
src/rootPages/Designer/ui_work_object_list_newObject_netsuite_dataTest.js
src/rootPages/Designer/ui_work_object_list_newObject_netsuite_fields.js
src/rootPages/Designer/ui_work_object_list_newObject_netsuite_tables.js
src/rootPages/Designer/ui_work_object_workspace.js
src/rootPages/Designer/ui_work_object_workspace_popupNewDataField.js

This is the current ABObjectAPINetsuite code for testing with the Team Org Chart.
Note: this will require `api_sails`, `appbuilder`, and `definition_manager` repos to be on `jh/Netsuite branches` to run properly.

Current Netsuite API code

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

Mostly switch Select List -> Connected Record Fields.
Note: I think we have different eslint settings. Did you change your eslint config? It looks the same to me: https://github.com/digi-serve/plugin_ABDesigner/blob/nh/teams-chart/.eslintrc.js
-

Fix data types to match real data

---

src/rootPages/Designer/editors/EditorManager.js
src/rootPages/Designer/editors/views/ABViewDataSelect.js
src/rootPages/Designer/properties/PropertyManager.js
src/rootPages/Designer/properties/views/ABViewDataSelect.js

Needed for https://github.com/digi-serve/planning/issues/578
Other PRs:
https://github.com/digi-serve/ab_platform_web/pull/591
https://github.com/digi-serve/appbuilder_class_core/pull/268
- Add widget to set cursor in a Datacollection

Add widget to set cursor in DC

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

https://github.com/digi-serve/planning/issues/578
Related: https://github.com/digi-serve/ab_platform_web/pull/592
- add entity datacollection setting

add entity dc setting

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

- Add start date and end date fields.

Add start date and end date fields

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

Limit edit form's fields

---

src/rootPages/Designer/properties/views/ABViewOrgChartTeams.js

- allow picking any color
- fix saving color when other settings change

Fix save colors and allow custom colors

---

src/rootPages/Designer/properties/process/ABProcessParticipant_selectManagersUI.js
src/rootPages/Designer/properties/process/ABProcessTaskUserExternal.js

- Fix the to user properties of External Approval task not populating

Fix populating toUsers property

---

src/rootPages/Designer/properties/process/ABProcessGatewayExclusive.js

https://github.com/digi-serve/ns_app/issues/602
- Prevent duplicates outgoing connections

*Prevent duplicate

---

src/rootPages/Designer/properties/process/ABProcessGatewayExclusive.js

https://github.com/digi-serve/ns_app/issues/602#issuecomment-2837491592
- Fix Gateway editor

*Fix Gateway editor

---

src/rootPages/Designer/properties/process/ABProcessGatewayExclusive.js

https://github.com/digi-serve/ns_app/issues/602
- Fix undefined

*Fix undefined
